var string_Manage = '<div id="ManageMain" align=center>';
string_Manage +=  '       <h2>Create Team</h2>';
string_Manage +=  '      <form onSubmit="event.preventDefault(); addTeam(); return false;" method="get">';
string_Manage +=  '        <p>Team Name:</p><input type="text" name="MTeamName" id="MTeamName"><br><br>';
string_Manage +=  '        <input type="submit" value="Create Team" name="submit">';
string_Manage +=  '      </form>';
string_Manage +=  '      <hr>';
string_Manage +=  '      <h2>Edit Team</h2>';
string_Manage +=  '      <p>Select A Team:</p>';
string_Manage +=  '      <div id="MTeamList"></div>';
string_Manage +=  '		</div>';
string_Manage +=  '		<div id="ManageRight">';
string_Manage +=  '      <div align=center>';
string_Manage +=  '        <!-- <div id="MRefreshButton">';
string_Manage +=  '          <img onmouseover="document.body.style.cursor = \'pointer\';"';
string_Manage +=  '                  onmouseout="document.body.style.cursor = \'default\';"';
string_Manage +=  '                  src="Images/refresh.gif" onclick=Refresh()>';
string_Manage +=  '        </div> -->';
string_Manage +=  '        <h2>Team Information</h2>';
string_Manage +=  '        <div id="MTeamTitle">Please select a team name.</div><br>';
string_Manage +=  '        <div id="MTeamTable">';
string_Manage +=  '          <div name="MStudent1" id="MStudent1" class="MStudentInfo">';
string_Manage +=  '            <h3>Student 1</h3>';
string_Manage +=  '            <form id="MForm1" onSubmit="event.preventDefault(); modifyStudent(\'Username_S1\', \'Stud1\'); return false;" method="get">';
string_Manage +=  '              <label>Name:</label><br>';
string_Manage +=  '                <div id="Member1">';
string_Manage +=  '                  <select name="Stud1" id="Stud1" class="MStudentSelect" onchange="currentSelection(this.value)">';
string_Manage +=  '                  <option>------Select a Name------</option>';
string_Manage +=  '                  </select>';
string_Manage +=  '                </div>';
string_Manage +=  '                <!-- <input type="text" name="Name_S1" id="Name_S1" value="John Doe" class="text"><br> -->';
string_Manage +=  '              <label>Username:</label><br>';
string_Manage +=  '				<input type="text" name="Username_S1" id="Username_S1" value="BugMaster1337" class="Mtext" readonly="readonly"><br>';
string_Manage +=  '              <label>School:</label><br>';
string_Manage +=  '				<input type="text" name="School_S1" id="School_S1" value="Example University" class="Mtext" readonly="readonly"><br>';
string_Manage +=  '              <label>State:</label><br>';
string_Manage +=  '				<input type="text" name="State_S1" id="State_S1" value="NW" class="Mtext" readonly="readonly"><br>';
string_Manage +=  '                <input type="hidden" name="selectName" id="selectName" value="Stud1">';
string_Manage +=  '              <input type="submit" value="Add" name="add1" id="add1" class="Mbutton">';
string_Manage +=  '              <input type="submit" value="Remove" name="remove1" id="remove1" class="Mbutton">';
string_Manage +=  '            </form>';
string_Manage +=  '          </div>';
string_Manage +=  '          <div name="MStudent2" id="MStudent2" class="MStudentInfo">';
string_Manage +=  '            <h3>Student 2</h3>';
string_Manage +=  '            <form id="MForm2" onSubmit="event.preventDefault(); modifyStudent(\'Username_S2\', \'Stud2\'); return false;" method="get">';
string_Manage +=  '              <label>Name:</label><br>';
string_Manage +=  '                <div id="Member2">';
string_Manage +=  '                  <select name="Stud2" id="Stud2" class="MStudentSelect" onchange="currentSelection(this)">';
string_Manage +=  '                  <option>------Select a Name------</option>';
string_Manage +=  '                  </select>';
string_Manage +=  '                </div>';
string_Manage +=  '                <!-- <input type="text" name="Name_S1" id="Name_S1" value="Jane Doe" class="text"><br> -->';
string_Manage +=  '              <label>Username:</label><br>';
string_Manage +=  '                <input type="text" name="Username_S2" id="Username_S2" value="Insecticider" class="Mtext" readonly="readonly"><br>';
string_Manage +=  '              <label>School:</label><br>';
string_Manage +=  '				<input type="text" name="School_S2" id="School_S2" value="Example University" class="Mtext" readonly="readonly"><br>';
string_Manage +=  '              <label>State:</label><br>';
string_Manage +=  '				<input type="text" name="State_S2" id="State_S2" value="NW" class="Mtext" readonly="readonly"><br>';
string_Manage +=  '                <input type="hidden" name="selectName" id="selectName" value="Stud2">';
string_Manage +=  '              <input type="submit" value="Add" name="add2" id="add2" class="Mbutton">';
string_Manage +=  '              <input type="submit" value="Remove" name="remove2" id="remove2" class="Mbutton">';
string_Manage +=  '            </form>';
string_Manage +=  '          </div>';
string_Manage +=  '          <div name="MStudent3" id="MStudent3" class="MStudentInfo">';
string_Manage +=  '            <h3>Student 3</h3>';
string_Manage +=  '            <form id="MForm3" onSubmit="event.preventDefault(); modifyStudent(\'Username_S3\', \'Stud3\'); return false;" method="get">';
string_Manage +=  '              <label>Name:</label><br>';
string_Manage +=  '                <div id="Member3">';
string_Manage +=  '                  <select name="Stud3" id="Stud3" class="MStudentSelect" onchange="currentSelection(this)">';
string_Manage +=  '                  <option>------Select a Name------</option>';
string_Manage +=  '                  </select>';
string_Manage +=  '                </div>';
string_Manage +=  '                <!-- <input type="text" name="Name_S1" id="Name_S1" value="Randall Munroe" class="text"><br> -->';
string_Manage +=  '              <label>Username:</label><br>';
string_Manage +=  '                <input type="text" name="Username_S3" id="Username_S3" value="DenverCoder9" class="Mtext" readonly="readonly"><br>';
string_Manage +=  '              <label>School:</label><br>';
string_Manage +=  '				<input type="text" name="School_S3" id="School_S3" value="Example University" class="Mtext" readonly="readonly"><br>';
string_Manage +=  '              <label>State:</label><br>';
string_Manage +=  '				<input type="text" name="State_S3" id="State_S3" value="NW" class="Mtext" readonly="readonly"><br>';
string_Manage +=  '               <input type="hidden" name="selectName" id="selectName" value="Stud3">';
string_Manage +=  '			';
string_Manage +=  '			  <input type="submit" value="Add" name="add3" id="add3" class="Mbutton">';
string_Manage +=  '			 ';
string_Manage +=  '			  <input type="submit" value="Remove" name="remove3" id="remove3" class="Mbutton">';
string_Manage +=  '			  ';
string_Manage +=  '            </form>';
string_Manage +=  '          </div>';
string_Manage +=  '        </div>        ';
string_Manage +=  '      </div>';
string_Manage +=  '    </div>';
