var string_states = '<select name="Registrationstate" id="Registrationstate" class="Iselect">';
string_states +=  '	<option value="N/A">Select a State</option>';
string_states +=  '	<option value="AL">Alabama</option>';
string_states +=  '	<option value="AK">Alaska</option>';
string_states +=  '	<option value="AZ">Arizona</option>';
string_states +=  '	<option value="AR">Arkansas</option>';
string_states +=  '	<option value="CA">California</option>';
string_states +=  '	<option value="CO">Colorado</option>';
string_states +=  '	<option value="CT">Connecticut</option>';
string_states +=  '	<option value="DE">Delaware</option>';
string_states +=  '	<option value="DC">District of Columbia</option>';
string_states +=  '	<option value="FL">Florida</option>';
string_states +=  '	<option value="GA">Georgia</option>';
string_states +=  '	<option value="HI">Hawaii</option>';
string_states +=  '	<option value="ID">Idaho</option>';
string_states +=  '	<option value="IL">Illinois</option>';
string_states +=  '	<option value="IN">Indiana</option>';
string_states +=  '	<option value="IA">Iowa</option>';
string_states +=  '	<option value="KS">Kansas</option>';
string_states +=  '	<option value="KY">Kentucky</option>';
string_states +=  '	<option value="LA">Louisiana</option>';
string_states +=  '	<option value="ME">Maine</option>';
string_states +=  '	<option value="MD">Maryland</option>';
string_states +=  '	<option value="MA">Massachusetts</option>';
string_states +=  '	<option value="MI">Michigan</option>';
string_states +=  '	<option value="MN">Minnesota</option>';
string_states +=  '	<option value="MS">Mississippi</option>';
string_states +=  '	<option value="MO">Missouri</option>';
string_states +=  '	<option value="MT">Montana</option>';
string_states +=  '	<option value="NE">Nebraska</option>';
string_states +=  '	<option value="NV">Nevada</option>';
string_states +=  '	<option value="NH">New Hampshire</option>';
string_states +=  '	<option value="NJ">New Jersey</option>';
string_states +=  '	<option value="NM">New Mexico</option>';
string_states +=  '	<option value="NY">New York</option>';
string_states +=  '	<option value="NC">North Carolina</option>';
string_states +=  '	<option value="ND">North Dakota</option>';
string_states +=  '	<option value="OH">Ohio</option>';
string_states +=  '	<option value="OK">Oklahoma</option>';
string_states +=  '	<option value="OR">Oregon</option>';
string_states +=  '	<option value="PA">Pennsylvania</option>';
string_states +=  '	<option value="RI">Rhode Island</option>';
string_states +=  '	<option value="SC">South Carolina</option>';
string_states +=  '	<option value="SD">South Dakota</option>';
string_states +=  '	<option value="TN">Tennessee</option>';
string_states +=  '	<option value="TX">Texas</option>';
string_states +=  '	<option value="UT">Utah</option>';
string_states +=  '	<option value="VT">Vermont</option>';
string_states +=  '	<option value="VA">Virginia</option>';
string_states +=  '	<option value="WA">Washington</option>';
string_states +=  '	<option value="WV">West Virginia</option>';
string_states +=  '	<option value="WI">Wisconsin</option>';
string_states +=  '	<option value="WY">Wyoming</option>';
string_states +=  '</select>';
