<?php

require_once dirname(__FILE__) . '/../../Models/Admin.php';
require_once dirname(__FILE__) . '/../../Models/Problem.php';

/**
 * Test class for Admin.
 * Generated by PHPUnit on 2012-06-14 at 10:01:46.
 */
class AdminTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Admin
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Admin(5); 
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    public function testRegisterAdmin()
    {
        //Admin::registerAdmin(array('username' => 'admin', 'password' => 'password', 'nickname' => 'adz'));
    }
    
    public function testFields()
    {
        //$this->assertSame($this->object->nickname, 'adz');
    }
    
    public function testLogin()
    {
        $this->assertNotEquals(Admin::login('admin', 'password'), FALSE);
    }
    
    public function testAddCompetition()
    {
        $this->object->createCompetition(array('compname' => 'jgifd'), array(new Problem(2), new Problem(5)));
    }
    
    public function testGetCompitions()
    {
        //var_dump($this->object->getCompetitions());
    }
    
     public function testGetCompitionsByName()
    {
        var_dump($this->object->getCompetitionByCompName("123")->starttime);
    }
    
   

}

?>