<?php

require_once dirname(__FILE__) . '/../../Models/Bug.php';

/**
 * Test class for Bug.
 * Generated by PHPUnit on 2012-06-14 at 14:23:36.
 */
class BugTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Bug
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
	$this->object = new Bug(1);
    }

    
    public function testFields(){
	$this->assertNotNull($this->object);
	$this->assertSame($this->object->bugnumber, '1');
	$this->assertSame($this->object->problemid, '1');
	$this->assertSame($this->object->description, 'really hard');
    }
    
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
	
    }

}

?>
