var string_Setup = '<div id="CompLeft">';
string_Setup +=  '  <h2>Competition Settings</h2>';
string_Setup +=  '  <div id="CsetupForm">';
string_Setup +=  '    <form name="CompForm" id="CompForm" onSubmit="event.preventDefault(); createCompetition(); return false;" method="GET">';
string_Setup +=  '      <u>Allow Code Coverage</u><br />';
string_Setup +=  '      <div class="Cradio-container">';
string_Setup +=  '        <input type="radio" class="Cradio-left" name="AllowCoverage" id="AllowCoverage" value="1" /> Yes ';
string_Setup +=  '        <input type="radio" class="Cradio-right" name="AllowCoverage" id="AllowCoverage" value="0" checked /> No ';
string_Setup +=  '      </div><br />';
string_Setup +=  '	<u>Include Countdown</u><br />';
string_Setup +=  '		<div class="Cradio-container">';
string_Setup +=  '		  <input type="radio" class="Cradio-left" name="IncludeCountdown" id="IncludeCountdown" value="1"/> Yes ';
string_Setup +=  '		  <input type="radio" class="Cradio-right" name="IncludeCountdown" id="IncludeCountdown" value="0" checked /> No';
string_Setup +=  '		</div><br />';
string_Setup +=  '      <span class="reqField">\&#10029;</span><u>Competition Time (mins)</u><br />';
string_Setup +=  '      <input name="CompTime" id="CompTime" class="Ctext" /><br />';
string_Setup +=  '';
string_Setup +=  '      <u>Competition ID</u><br />';
string_Setup +=  '      <input name="CompNameID" id="CompNameID" class="Ctext" /><br />';
string_Setup +=  '';
string_Setup +=  '      <input type="submit" value="Setup Competition" name="CSetupButton" id="CSetupButton" class="Cbutton" /><br /><br />';
string_Setup +=  '      ';
string_Setup +=  '    </form>';
string_Setup +=  '    <div id="CSetupError" class="Cerror-normal"></div>';
string_Setup +=  '  </div>';
string_Setup +=  '</div>';
string_Setup +=  '<div id="CompRight">';
string_Setup +=  '  <h2>Problem Selection</h2>';
string_Setup +=  '  <form>';
string_Setup +=  '      <u>Available Problems</u><br />';
string_Setup +=  '      <div id="ProblemsList">';
string_Setup +=  '      <select name="ProblemsList" class="Cselect" size="8">';
string_Setup +=  '      </select></div>';
string_Setup +=  '      ';
string_Setup +=  '      <u>Selected Problems</u><br />';
string_Setup +=  '      <div id="SelectedProblems">';
string_Setup +=  '      <select name="SelectedProblems" class="Cselect"  size="5">';
string_Setup +=  '      </select></div>';
string_Setup +=  '      ';
string_Setup +=  '      <input type="submit" value="Move Up" name="CMoveUp" id="CMoveUp" class="Cbutton-small" onClick="event.preventDefault(); moveProbUp(SelectedProblemsGet.value)" />';
string_Setup +=  '      <input type="submit" value="Move Down" name="CMoveDown" id="CMoveDown" class="Cbutton-small" onClick="event.preventDefault(); moveProbDown(SelectedProblemsGet.value)" />';
string_Setup +=  '   </form>';
string_Setup +=  '</div>';
string_Setup +=  '<div id="CompMiddle">';
string_Setup +=  '  <h2>Problem Preview</h2> ';
string_Setup +=  '  <div id="CPreview">';
string_Setup +=  '    <textarea cols="54" rows="18" id="CTextArea" disabled></textarea>          ';
string_Setup +=  '    <form onSubmit="event.preventDefault(); return false;" method="get">';
string_Setup +=  '        <input type="submit" id="aBut" value="Add Problem" onClick="addProb(ProblemsListGet.value)" name="submit" class="Cbutton-preview"/>';
string_Setup +=  '        <input type="submit" id="rBut" value="Remove Problem" onClick="removeProb(SelectedProblemsGet.value)" name="submit"  class="Cbutton-preview" />';
string_Setup +=  '    </form>';
string_Setup +=  '  </div>';
string_Setup +=  '</div>';
