var string_Hints = '<div id="CustomHeader" align=center>';
string_Hints +=  '      <h2>Custom Hint</h2>';
string_Hints +=  '    </div>';
string_Hints +=  '    <div id="PreDefHeader" align=center>';
string_Hints +=  '      <h2>PreDef Hint</h2>';
string_Hints +=  '    </div>';
string_Hints +=  '		<div id="HintsLeft" align=center>';
string_Hints +=  '      <p>Enter a Custom Hint:</p>';
string_Hints +=  '	  <form onsubmit="event.preventDefault(); sendHintsCust(CustomHint.value); " method="get">';
string_Hints +=  '      <textarea name="CustomHint" id="CustomHint" onfocus="if(this.value==this.defaultValue) {this.value=\'\';}" wrap="physical">Custom Hints (click here)\n';
string_Hints +=  '      </textarea ><br>';
string_Hints +=  '      <input type="submit" name="submitCust" id="SendCustom" value="Send Custom Hint" class="Hbutton">';
string_Hints +=  '	  </form >';
string_Hints +=  '		</div>';
string_Hints +=  '		<div id="HintsRight" align=center>';
string_Hints +=  '      <div id="HintsPreDefTop">';
string_Hints +=  '        <div id="HintsPreDefRight">';
string_Hints +=  '          <p>Select Hint to View:</p>';
string_Hints +=  '          <div id="HintNum" > <select name="HHintNum" id="HHintNum" size=7 class="Hselect">';
string_Hints +=  '            ';
string_Hints +=  '          </select>';
string_Hints +=  '		 </div>';
string_Hints +=  '		';
string_Hints +=  '        </div>';
string_Hints +=  '        <div id="HintsPreDefLeft">';
string_Hints +=  '          <p>Select Problem Number:</p>';
string_Hints +=  ' 			<div id="probNamesHints"> ';
string_Hints +=  '          	<select name="HProbNum" id="HProbNum" size=5 class="Hselect" onchange=showPre(this.value);>';
string_Hints +=  '          	</select>';
string_Hints +=  ' 			</div>';
string_Hints +=  '        </div>';
string_Hints +=  '      </div>';
string_Hints +=  '      <div id="HintsPreDefBottom">';
string_Hints +=  '        <div id="HintText">';
string_Hints +=  '          <p>Hint text will appear here when hint number is selected.</p>';
string_Hints +=  '        </div>';
string_Hints +=  '		<form onsubmit="event.preventDefault(); sendHintPreDef();">';
string_Hints +=  '        <input type="submit" name="SendPreDef" id="SendPreDef" value="Send Pre-Defined Hint" class="Hbutton">';
string_Hints +=  '		</form>';
string_Hints +=  '      </div>';
string_Hints +=  '		</div>';
